---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted

- name: Restart apt-cacher-ng
  ansible.builtin.systemd:
    name: apt-cacher-ng
    state: restarted
